"""spread columns on token_prices (ADR-020)

Revision ID: 047e70d67c1e
Revises: 77dc5a0edb5e
Create Date: 2026-09-01 14:00:10.463852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '047e70d67c1e'
down_revision: Union[str, Sequence[str], None] = '77dc5a0edb5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_prices', sa.Column('bid_usd', sa.Numeric(precision=28, scale=10), nullable=True))
    op.add_column('token_prices', sa.Column('ask_usd', sa.Numeric(precision=28, scale=10), nullable=True))
    op.add_column('token_prices', sa.Column('bid_impact_pct', sa.Numeric(precision=18, scale=10), nullable=True))
    op.add_column('token_prices', sa.Column('ask_impact_pct', sa.Numeric(precision=18, scale=10), nullable=True))
    op.add_column('token_prices', sa.Column('quote_size_usd', sa.Numeric(precision=28, scale=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_prices', 'quote_size_usd')
    op.drop_column('token_prices', 'ask_impact_pct')
    op.drop_column('token_prices', 'bid_impact_pct')
    op.drop_column('token_prices', 'ask_usd')
    op.drop_column('token_prices', 'bid_usd')
    # ### end Alembic commands ###
