"""initial ledger tables

The first migration: the five tables of ADR-014 — audit_log, order_intents,
fills, lots, realized_pnl. Autogenerated from models.py and left as generated,
because at this point the models *are* the specification.

Money columns are NUMERIC(28,10), never DOUBLE PRECISION (ADR-010).
Timestamps are all `timestamptz`.

Revision ID: 652bca1ec5a7
Revises:
Create Date: 2026-08-27 12:02:17.511916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '652bca1ec5a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=64), nullable=False),
    sa.Column('alpaca_account_id', sa.String(length=64), nullable=True),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=8), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.CheckConstraint("outcome in ('ok','error')", name=op.f('ck_audit_log_outcome')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_audit_log_request_id'), 'audit_log', ['request_id'], unique=False)
    op.create_index('ix_audit_log_user_at', 'audit_log', ['clerk_user_id', 'at'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('alpaca_activity_id', sa.String(length=128), nullable=False),
    sa.Column('alpaca_account_id', sa.String(length=64), nullable=False),
    sa.Column('alpaca_order_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('qty', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fills')),
    sa.UniqueConstraint('alpaca_activity_id', name=op.f('uq_fills_alpaca_activity_id'))
    )
    op.create_index('ix_fills_account_occurred', 'fills', ['alpaca_account_id', 'occurred_at'], unique=False)
    op.create_index('ix_fills_account_symbol', 'fills', ['alpaca_account_id', 'symbol'], unique=False)
    op.create_table('order_intents',
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=64), nullable=False),
    sa.Column('body_sha256', sa.String(length=64), nullable=False),
    sa.Column('alpaca_order_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key', name=op.f('pk_order_intents'))
    )
    op.create_index(op.f('ix_order_intents_clerk_user_id'), 'order_intents', ['clerk_user_id'], unique=False)
    op.create_table('lots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('alpaca_account_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('opened_by_fill_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('qty_open', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('qty_initial', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['opened_by_fill_id'], ['fills.id'], name=op.f('fk_lots_opened_by_fill_id_fills'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lots')),
    sa.UniqueConstraint('opened_by_fill_id', name=op.f('uq_lots_opened_by_fill_id'))
    )
    op.create_index('ix_lots_account_symbol_opened', 'lots', ['alpaca_account_id', 'symbol', 'opened_at'], unique=False)
    op.create_table('realized_pnl',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('alpaca_account_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('sell_fill_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('qty', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('proceeds', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('realized', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sell_fill_id'], ['fills.id'], name=op.f('fk_realized_pnl_sell_fill_id_fills'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_realized_pnl')),
    sa.UniqueConstraint('sell_fill_id', name=op.f('uq_realized_pnl_sell_fill_id'))
    )
    op.create_index('ix_realized_pnl_account_occurred', 'realized_pnl', ['alpaca_account_id', 'occurred_at'], unique=False)
    op.create_index('ix_realized_pnl_account_symbol', 'realized_pnl', ['alpaca_account_id', 'symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_realized_pnl_account_symbol', table_name='realized_pnl')
    op.drop_index('ix_realized_pnl_account_occurred', table_name='realized_pnl')
    op.drop_table('realized_pnl')
    op.drop_index('ix_lots_account_symbol_opened', table_name='lots')
    op.drop_table('lots')
    op.drop_index(op.f('ix_order_intents_clerk_user_id'), table_name='order_intents')
    op.drop_table('order_intents')
    op.drop_index('ix_fills_account_symbol', table_name='fills')
    op.drop_index('ix_fills_account_occurred', table_name='fills')
    op.drop_table('fills')
    op.drop_index('ix_audit_log_user_at', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_request_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
