"""weekend trades and events (ADR-019)

Revision ID: 77dc5a0edb5e
Revises: ae32e281aedd
Create Date: 2026-08-31 13:10:06.794353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77dc5a0edb5e'
down_revision: Union[str, Sequence[str], None] = 'ae32e281aedd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekend_trades',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('clerk_user_id', sa.String(length=64), nullable=False),
    sa.Column('alpaca_account_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('token_symbol', sa.String(length=16), nullable=False),
    sa.Column('mint', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('qty', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('p_open', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('sigma', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('z', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('reserve', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('fees', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('escrow_journal_id', sa.String(length=64), nullable=True),
    sa.Column('advance_journal_id', sa.String(length=64), nullable=True),
    sa.Column('settlement_mode', sa.String(length=16), nullable=True),
    sa.Column('injected_gap', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('hedge_order_id', sa.String(length=64), nullable=True),
    sa.Column('p_close', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('true_up', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('escrow_returned', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('shortfall', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("side in ('buy','sell')", name=op.f('ck_weekend_trades_side')),
    sa.CheckConstraint("state in ('provisional','awaiting_settlement','settled','breached')", name=op.f('ck_weekend_trades_state')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekend_trades'))
    )
    op.create_index('ix_weekend_trades_account_created', 'weekend_trades', ['alpaca_account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_weekend_trades_created_at'), 'weekend_trades', ['created_at'], unique=False)
    op.create_index('ix_weekend_trades_state', 'weekend_trades', ['state'], unique=False)
    op.create_table('weekend_trade_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('alpaca_ref', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['weekend_trades.id'], name=op.f('fk_weekend_trade_events_trade_id_weekend_trades'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekend_trade_events'))
    )
    op.create_index('ix_weekend_trade_events_trade_at', 'weekend_trade_events', ['trade_id', 'at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weekend_trade_events_trade_at', table_name='weekend_trade_events')
    op.drop_table('weekend_trade_events')
    op.drop_index('ix_weekend_trades_state', table_name='weekend_trades')
    op.drop_index(op.f('ix_weekend_trades_created_at'), table_name='weekend_trades')
    op.drop_index('ix_weekend_trades_account_created', table_name='weekend_trades')
    op.drop_table('weekend_trades')
    # ### end Alembic commands ###
