"""token_candles and market_bars

ADR-016/017: the historical backfill behind sigma_gap. token_candles holds
GeckoTerminal's hourly and daily OHLCV for each xStock's deepest USDC pool
(the token's weekend past, 180 days of it); market_bars holds Alpaca's daily
bars for the real share and the Monday 04:00-10:30 ET minute bars where the
gap is settled. Both upserted on a natural key, never updated.

Revision ID: ae32e281aedd
Revises: d0414336c902
Create Date: 2026-08-28 13:22:26.524346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae32e281aedd'
down_revision: Union[str, Sequence[str], None] = 'd0414336c902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_bars',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('high', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('low', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('close', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('volume', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_bars')),
    sa.UniqueConstraint('symbol', 'timeframe', 'bucket_start', name=op.f('uq_market_bars_symbol_timeframe_bucket_start'))
    )
    op.create_index('ix_market_bars_symbol_timeframe_bucket', 'market_bars', ['symbol', 'timeframe', 'bucket_start'], unique=False)
    op.create_table('token_candles',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('mint', sa.String(length=64), nullable=False),
    sa.Column('pool', sa.String(length=64), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('high', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('low', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('close', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('volume_usd', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_candles')),
    sa.UniqueConstraint('pool', 'timeframe', 'bucket_start', name=op.f('uq_token_candles_pool_timeframe_bucket_start'))
    )
    op.create_index('ix_token_candles_symbol_timeframe_bucket', 'token_candles', ['symbol', 'timeframe', 'bucket_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_candles_symbol_timeframe_bucket', table_name='token_candles')
    op.drop_table('token_candles')
    op.drop_index('ix_market_bars_symbol_timeframe_bucket', table_name='market_bars')
    op.drop_table('market_bars')
    # ### end Alembic commands ###
