"""token_prices

ADR-016: one table for the xStock price sampler. Every five minutes, each
tokenized stock's Jupiter price is recorded beside its real share's last
trade on Alpaca. Append-only; the raw material for sigma_gap.

Revision ID: d0414336c902
Revises: 652bca1ec5a7
Create Date: 2026-08-28 13:07:57.129937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0414336c902'
down_revision: Union[str, Sequence[str], None] = '652bca1ec5a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_prices',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('underlying', sa.String(length=16), nullable=True),
    sa.Column('mint', sa.String(length=64), nullable=False),
    sa.Column('usd_price', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('liquidity_usd', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('block_id', sa.BigInteger(), nullable=True),
    sa.Column('price_change_24h', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('market_price', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('market_trade_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('market_open', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_prices'))
    )
    op.create_index(op.f('ix_token_prices_sampled_at'), 'token_prices', ['sampled_at'], unique=False)
    op.create_index('ix_token_prices_symbol_sampled', 'token_prices', ['symbol', 'sampled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_prices_symbol_sampled', table_name='token_prices')
    op.drop_index(op.f('ix_token_prices_sampled_at'), table_name='token_prices')
    op.drop_table('token_prices')
    # ### end Alembic commands ###
